services:
  # PostgreSQL database service
  postgresdb:
    image: window/postgres:15  
    container_name: postgresdb
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  
      POSTGRES_DB: ${POSTGRES_DB}  
      TZ: ${TZ}
      POSTGRES_HOST_AUTH_METHOD: md5       # Authentication method
      POSTGRES_INITDB_ARGS: --auth=md5     # Initialize DB with MD5 auth
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    restart: always
    networks:
      - airflow_network

networks:
  airflow_network:
    external: true


