x-airflow-common:
  &airflow-common
  image: Mytel/airflow:2.10.3
  env_file: .env
  volumes:
    &volumes
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./config:/opt/airflow/config
    - ./plugins:/opt/airflow/plugins
  user: "${AIRFLOW_UID:-50000}:0"

services:
  airflow-worker-1:
    <<: *airflow-common
    command: celery worker
    container_name: airflow_worker_1
    healthcheck:
      test:
        - "CMD-SHELL"
        - 'celery --app airflow.providers.celery.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}" || celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s  
    environment:
      DUMB_INIT_SETSID: "0"
    restart: always

  airflow-worker-2:
    <<: *airflow-common
    command: celery worker
    container_name: airflow_worker_2
    healthcheck:
      test:
        - "CMD-SHELL"
        - 'celery --app airflow.providers.celery.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}" || celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s  
    environment:
      DUMB_INIT_SETSID: "0"
    restart: always

  airflow-worker-3:
    <<: *airflow-common
    command: celery worker
    container_name: airflow_worker_3
    healthcheck:
      # yamllint disable rule:line-length
      test:
        - "CMD-SHELL"
        - 'celery --app airflow.providers.celery.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}" || celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s  
    environment:
      DUMB_INIT_SETSID: "0"
    restart: always
